### PR TITLE
Fix sanitisers compilation in PR#113

### PR DESCRIPTION
**Pull request by dcillera**
Compilation option for sanitisers added in cmake configuration

### CODE REVIEW

**Review by tedjpoole — COMMENTED** [review]
I think we also need a `target_compile_options(...)` for the `bssl-compat` library target

**Comment by dcillera** [comment]
> I think we also need a `target_compile_options(...)` for the `bssl-compat` library target

And `target_link_options` too?

**Comment by tedjpoole** [comment]
@dcillera do you want to continue with this PR, or do you think it would be better to start another using the work you subsequently did using [arsenm/sanitizers-cmake](https://github.com/arsenm/sanitizers-cmake)?

**Comment by dcillera** [comment]
@tedjpoole I think it's better to create a new one.

**Comment by tedjpoole** [comment]
Superseded by #121

**Pull request closed without merging**
